# Generated by Django 5.1.7 on 2025-03-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="Category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="create_by",
            new_name="created_by",
        ),
    ]
